-- Stefan-Octavian Radu - grupa 234

-- 9

SELECT FIRST_NAME, LAST_NAME, t.TITLE, COUNT(r.BOOK_DATE) 
FROM "MEMBER" m 
JOIN RENTAL r
	ON m.MEMBER_ID = r.MEMBER_ID
JOIN TITLE t 
	ON t.TITLE_ID = r.TITLE_ID 
GROUP BY m.FIRST_NAME, m.LAST_NAME, t.TITLE
ORDER BY t.TITLE ASC;

-- 10

SELECT FIRST_NAME, LAST_NAME, t.TITLE_ID , COUNT(r.BOOK_DATE) 
FROM "MEMBER" m 
JOIN RENTAL r
	ON m.MEMBER_ID = r.MEMBER_ID
JOIN TITLE t 
	ON t.TITLE_ID = r.TITLE_ID 
GROUP BY m.FIRST_NAME, m.LAST_NAME, t.TITLE_ID 
ORDER BY t.TITLE_ID ASC;

-- 11

WITH 
AUX1 AS (
	SELECT tc.TITLE_ID, tc.COPY_ID, count(tc.TITLE_ID) cnt, tc.STATUS
	FROM RENTAL r
	JOIN TITLE_COPY tc ON tc.TITLE_ID = r.TITLE_ID AND tc.COPY_ID = r.COPY_ID
	GROUP BY tc.COPY_ID, tc.TITLE_ID, tc.STATUS
	ORDER BY tc.TITLE_ID 
),
AUX2 AS (
	SELECT t.TITLE_ID, TITLE, max(CNT) MAX_CNT
	FROM AUX1 a
	JOIN TITLE t ON t.TITLE_ID = a.TITLE_ID
	GROUP BY t.TITLE_ID, TITLE
)
SELECT a2.TITLE, a1.status
FROM AUX1 a1
JOIN AUX2 a2 ON a1.TITLE_ID = a2.TITLE_ID AND CNT = MAX_CNT
GROUP BY a1.TITLE_ID, a2.TITLE, a1.STATUS

-- 12 a

SELECT TO_CHAR(r.BOOK_DATE, 'dd') day, count(*) how_many
FROM rental r
WHERE TO_CHAR(r.BOOK_DATE, 'mm') = TO_CHAR(sysdate, 'mm') AND 
	  TO_CHAR(r.BOOK_DATE, 'dd') <= 2
GROUP BY TO_CHAR(r.BOOK_DATE, 'dd') 

-- 12 b

SELECT TO_CHAR(r.BOOK_DATE, 'dd') day, count(*) how_many
FROM rental r
WHERE TO_CHAR(r.BOOK_DATE, 'mm') = TO_CHAR(sysdate, 'mm')
GROUP BY TO_CHAR(r.BOOK_DATE, 'dd') 
